name: casualapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.7
  animated_text_kit: ^4.2.2
  page_transition: ^2.0.9
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_glow.png
    - assets/images/button_back.png
    - assets/images/button_close.png
    - assets/images/button_arrow_right.png
    - assets/images/icon_coin.png
    - assets/images/icon_coin_large.png
    - assets/images/icon_star.png
    - assets/images/icon_info.png
    - assets/images/icon_money.png
    - assets/images/icon_timer.png
    - assets/images/icon_check_mark.png
    - assets/images/splash_screen/1.png
    - assets/images/splash_screen/2.png
    - assets/images/splash_screen/img.png
    - assets/images/splash_screen/bg.png
    - assets/images/splash_screen/fade.png
    - assets/images/login_screen/bg.png
    - assets/images/login_screen/text.png
    - assets/images/login_screen/icon_apple.png
    - assets/images/login_screen/icon_google.png
    - assets/images/login_screen/icon_email.png
    - assets/images/signup_screen/icon_email_outlined.png
    - assets/images/signup_screen/icon_password_outlined.png
    - assets/images/signup_screen/icon_person.png
    - assets/images/signup_screen/icon_person_with_camera.png
    - assets/images/update_screen/icon_bell_with_1.png
    - assets/images/game_home_screen/top_bg_blur.png
    - assets/images/game_home_screen/earn_token_img_1.png
    - assets/images/game_home_screen/img_table_tennis.png
    - assets/images/game_home_screen/img_8_ball.png
    - assets/images/game_home_screen/img_8_ball_play.png
    - assets/images/game_home_screen/img_level.png
    - assets/images/game_home_screen/icon_games.png
    - assets/images/game_home_screen/icon_tournaments.png
    - assets/images/game_home_screen/icon_leaderboard.png
    - assets/images/game_home_screen/icon_transactions.png
    - assets/images/game_home_screen/game_3d_chess.png
    - assets/images/game_home_screen/game_8_ball_billiard.png
    - assets/images/game_home_screen/game_archery.png
    - assets/images/game_home_screen/game_city_dunk.png
    - assets/images/game_home_screen/game_endless_truck.png
    - assets/images/game_home_screen/game_totemia.png
    - assets/images/game_home_screen/game_table_tennis.png
    - assets/images/game_ranking_screen/badge_beginner.png
    - assets/images/game_ranking_screen/badge_warrior.png
    - assets/images/game_ranking_screen/badge_knight.png
    - assets/images/game_ranking_screen/badge_baron.png
    - assets/images/game_ranking_screen/badge_duke.png
    - assets/images/game_ranking_screen/badge_emperor.png
    - assets/images/game_ranking_screen/badge_master.png
    - assets/images/game_ranking_screen/badge_noble.png
    - assets/images/game_ranking_screen/badge_prince.png
    - assets/images/game_ranking_screen/badge_regen.png
    - assets/images/game_ranking_screen/icon_ranking_progress.png

  fonts:
    - family: Monument
      fonts:
        - asset: assets/fonts/MonumentExtended-Regular.otf
          weight: 400
        - asset: assets/fonts/MonumentExtended-Ultrabold.otf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
